// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for reasoning about incident response, 
 * automatically quarantining suspicious processes and isolating compromised files to minimize potential damage from attacks.
 *
 * - incidentResponseReasoning - A function that triggers the incident response reasoning flow.
 * - IncidentResponseReasoningInput - The input type for the incidentResponseReasoning function.
 * - IncidentResponseReasoningOutput - The return type for the incidentResponseReasoning function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { blockIpAddress, changeSystemSetting, uninstallProgram } from '../tools/system-actions';

const IncidentResponseReasoningInputSchema = z.object({
  incidentData: z.string().describe('Detailed data about the security incident, including logs, process states, and file descriptors.'),
  systemState: z.string().describe('Current state of the system, including running processes, network connections, and resource usage.'),
});
export type IncidentResponseReasoningInput = z.infer<typeof IncidentResponseReasoningInputSchema>;

const IncidentResponseReasoningOutputSchema = z.object({
  actions: z.array(
    z.object({
      actionType: z.enum(['quarantineProcess', 'isolateFile', 'noAction', 'blockIp', 'uninstallProgram', 'changeSetting']).describe('Type of action to take.'),
      target: z.string().describe('The process ID, file path, IP address, program name, or setting to action.'),
      reason: z.string().describe('The reasoning behind the action taken.'),
    })
  ).describe('A list of actions to take based on the incident analysis.'),
  summary: z.string().describe('A summary of the incident and the recommended actions.'),
});
export type IncidentResponseReasoningOutput = z.infer<typeof IncidentResponseReasoningOutputSchema>;

export async function incidentResponseReasoning(input: IncidentResponseReasoningInput): Promise<IncidentResponseReasoningOutput> {
  return incidentResponseReasoningFlow(input);
}

const prompt = ai.definePrompt({
  name: 'incidentResponseReasoningPrompt',
  input: {schema: IncidentResponseReasoningInputSchema},
  output: {schema: IncidentResponseReasoningOutputSchema},
  tools: [blockIpAddress, uninstallProgram, changeSystemSetting],
  prompt: `You are an expert security incident responder. Analyze the provided incident data and system state to determine the best course of action to mitigate the threat.

Incident Data:
{{incidentData}}

System State:
{{systemState}}

Based on your analysis, generate a list of actions to take. Use the available tools to perform actions like blocking IPs, uninstalling programs, or changing settings when necessary.
For each action, include:
- actionType: 'quarantineProcess', 'isolateFile', 'blockIp', 'uninstallProgram', 'changeSetting', or 'noAction'
- target: The process ID, file path, IP address, program name, or setting name to action.
- reason: A detailed explanation of why this action is necessary.

Finally, provide a summary of the incident and the recommended actions.

Ensure your response is well-reasoned and provides a clear justification for each action taken.

Output should be a JSON object with 'actions' and 'summary' fields, according to the schema description.
`,
});

const incidentResponseReasoningFlow = ai.defineFlow(
  {
    name: 'incidentResponseReasoningFlow',
    inputSchema: IncidentResponseReasoningInputSchema,
    outputSchema: IncidentResponseReasoningOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
